classification_task:
  description: >
    Lakukan klasifikasi terhadap {keluhan_user} untuk menentukan apakah informasi tersebut termasuk gejala atau penyakit.
    Hasil klasifikasi ini akan menentukan agen selanjutnya yang akan menangani kasus pengguna.
  expected_output: >
    Format JSON seperti berikut:
    {
      "label": "gejala",
      "data": {
      "gejala_user": "luka gores sehingga berdarah di tangan"
      }
    }

  agent: classification_agent

symptoms_analyzer_task:
  description: >
    Menganalisa gejala yang dilaporkan pengguna dan mendiagnosis penyakit berdasarkan gejala tersebut.
    Gunakan database CSV atau pengetahuan medis untuk meningkatkan akurasi diagnosis.
    Abaikan penyakit yang tidak memiliki hubungan langsung dengan gejala pengguna.
  expected_output: >
    Diagnosis utama, tingkat risiko penyakit, gejala terkait lainnya, dan efek samping umum.
    Urutkan penyakit berdasarkan relevansi tertinggi dengan gejala.
    Jika input tidak ada kaitannya dengan penyakit/gejala/obat, jawab: "Tidak ada kaitannya dengan penyakit, gejala, dan obat."
  agent: symptoms_analyzer_agent
  context: [classification_task]

drug_recommendation_task:
  description: >
    Berdasarkan daftar penyakit yang telah didiagnosis, berikan rekomendasi obat untuk masing-masing penyakit.
    Setiap penyakit harus memiliki: nama obat, dosis, aturan pakai, dan efek samping yang umum. Anda juga diminta untuk mencari tahu informasi tentang tingkat risiko penyakit dan gejala terkait lainnya.
  expected_output: >
    Untuk setiap penyakit:
    - Tingkat Risiko
    - Gejala Terkait
    - Nama penyakit
    - Nama obat
    - Dosis
    - Aturan pakai
    - Efek samping
  agent: virtual_pharmacist_agent
  context: [classification_task, symptoms_analyzer_task]


output_handler_task:
  description: >
    Merapikan output dari agent lain agar mudah dipahami manusia dalam format yang konsisten dan profesional.
  expected_output: >
    Rangkuman output agent lain dalam format yang ditentukan. Hilangkan tanda bintang pada output, dan berikan new line pada akhir baris. Contoh output:

    1. Nama Penyakit (dengan nama lokal jika ada)\n (sebutin aja nama penyakitnya tanpa format)
    - Tingkat Risiko: Tingkat Risiko Penyakit\n
    - Gejala Terkait: Daftar Gejala\n
    - Rekomendasi Obat:
      - Nama Obat: Nama Obat
      - Dosis: Dosis
      - Aturan Pakai: Aturan Pakai
      - Efek Samping Obat: Efek Samping dari Obat
  agent: output_handler_agent
  context: [symptoms_analyzer_task, drug_recommendation_task]