classification_task:
  description: >
    Jawablah menggunakan bahasa {language}.
    Lakukan klasifikasi terhadap {keluhan_user} untuk menentukan apakah informasi tersebut termasuk gejala atau penyakit.
    Hasil klasifikasi ini akan menentukan agen selanjutnya yang akan menangani kasus pengguna.
  expected_output: >
    Format JSON seperti berikut:
    {
      "label": "gejala",
      "data": {
      "gejala_user": "luka gores sehingga berdarah di tangan"
      }
    }

  agent: classification_agent

symptoms_analyzer_task:
  description: >
    Jawablah menggunakan bahasa {language}.
    Menganalisa gejala yang dilaporkan pengguna dan mendiagnosis penyakit berdasarkan gejala tersebut.
    Gunakan database CSV atau pengetahuan medis untuk meningkatkan akurasi diagnosis.
    Abaikan penyakit yang tidak memiliki hubungan langsung dengan gejala pengguna.
    Jawablah hanya berdasarkan konteks dataset CSV yang diberikan. Jika tidak ditemukan, katakan 'Tidak ditemukan'.
  expected_output: >
    Diagnosis utama, tingkat risiko penyakit, gejala terkait lainnya, dan efek samping umum. Berikan satu output penyakit saja yang paling relevan dengan gejala yang dilaporkan.
    Jika input tidak ada kaitannya dengan penyakit/gejala/obat, jawab: "Tidak ada kaitannya dengan penyakit, gejala, dan obat."
  agent: symptoms_analyzer_agent
  context: [classification_task]

drug_recommendation_task:
  description: >
    Jawablah menggunakan bahasa {language}.
    Berdasarkan penyakit yang telah didiagnosis, berikan  5 daftar rekomendasi obat untuk penyakit tersebut.
    Rekomendasi obat untuk Penyakit harus memiliki: nama obat, dosis, aturan pakai, dan efek samping yang umum. Anda juga diminta untuk mencari tahu informasi tentang tingkat risiko penyakit dan gejala terkait lainnya.
    Jawablah hanya berdasarkan konteks dataset CSV yang diberikan. Jika tidak ditemukan, katakan 'Tidak ditemukan'.
  expected_output: >
    Nama Penyakit: ...
    A. Nama Obat 1: ...
    - Tingkat Risiko
    - Gejala Terkait
    - Dosis
    - Aturan pakai
    - Efek samping
    B. Nama Obat 2: ...
    - Tingkat Risiko
    - Gejala Terkait
    - Dosis
    - Aturan pakai
    - Efek samping
    C. Nama Obat 3: ...
    - Tingkat Risiko
    - Gejala Terkait
    - Dosis
    - Aturan pakai
    - Efek samping
    D. Nama Obat 4: ...
    - Tingkat Risiko
    - Gejala Terkait
    - Dosis
    - Aturan pakai
    - Efek samping
    E. Nama Obat 5: ... 
    - Tingkat Risiko
    - Gejala Terkait
    - Dosis
    - Aturan pakai
    - Efek samping
    (Jawablah menggunakan bahasa {language}.)
  agent: virtual_pharmacist_agent
  context: [classification_task, symptoms_analyzer_task]


output_handler_task:
  description: >
    Jawablah menggunakan bahasa {language}.
    Merapikan output dari agent lain agar mudah dipahami manusia dalam format yang konsisten dan profesional.
  expected_output: >
    Rangkuman output agent lain dalam format yang ditentukan. Hilangkan tanda bintang atau simbol formatting lainnya pada output, dan berikan new line pada akhir baris. Contoh output:

    Nama Penyakit: Nama Penyakit (dengan nama lokal jika ada)\n (Sebutkan saja nama penyakitnya tanpa format)
    - Tingkat Risiko: Tingkat Risiko Penyakit\n
    - Gejala Terkait: Daftar Gejala\n
    A. Rekomendasi Obat 1: (Nama Obatnya)
      - Dosis: Dosis Obat 1
      - Aturan Pakai: Aturan Pakai Obat 1
      - Efek Samping Obat: Efek Samping dari Obat 1
    B. Rekomendasi Obat 2 (Bila ada lebih dari satu obat): (Nama Obatnya)
      - Dosis: Dosis Obat 2
      - Aturan Pakai: Aturan Pakai Obat 2
      - Efek Samping Obat: Efek Samping dari Obat 2
    C. Rekomendasi Obat 3 (Bila ada lebih dari satu obat): (Nama Obatnya)
      - Dosis: Dosis Obat 3
      - Aturan Pakai: Aturan Pakai Obat 3
      - Efek Samping Obat: Efek Samping dari Obat 3
    D. Rekomendasi Obat 4 (Bila ada lebih dari satu obat): (Nama Obatnya)
      - Dosis: Dosis Obat 4
      - Aturan Pakai: Aturan Pakai Obat 4
      - Efek Samping Obat: Efek Samping dari Obat 4
    E. Rekomendasi Obat 5 (Bila ada lebih dari satu obat): (Nama Obatnya)
      - Dosis: Dosis Obat 5
      - Aturan Pakai: Aturan Pakai Obat 5
      - Efek Samping Obat: Efek Samping dari Obat 5
    (Buat formatnya 5 obat secara absolut, bila tidak ada sampai 5 obat, kosongkan saja rekomendasi obatnya, Jawablah menggunakan bahasa {language}.)
  agent: output_handler_agent
  context: [symptoms_analyzer_task, drug_recommendation_task, classification_task]