classification_task:
  description: >
    Klasifikasikan input dari pengguna apakah termasuk gejala, penyakit, atau penyebab/faktor risiko.
    Informasi ini akan menentukan agen selanjutnya yang akan menangani kasus pengguna.
  expected_output: >
    Label klasifikasi dari input pengguna (gejala, penyakit, atau penyebab),
    serta informasi siap diteruskan ke agen analisa atau rekomendasi obat.
  agent: classification_agent

analisis_penyakit_dari_gejala_task:
  description: >
    Menganalisa gejala yang dilaporkan pengguna dan mendiagnosis penyakit berdasarkan gejala tersebut.
    Gunakan database CSV atau pengetahuan medis untuk meningkatkan akurasi diagnosis.
    Abaikan penyakit yang tidak memiliki hubungan langsung dengan gejala pengguna.
  expected_output: >
    Diagnosis utama, tingkat risiko penyakit, gejala terkait lainnya, dan efek samping umum.
    Urutkan penyakit berdasarkan relevansi tertinggi dengan gejala.
    Jika input tidak ada kaitannya dengan penyakit/gejala/obat, jawab: "Tidak ada kaitannya dengan penyakit, gejala, dan obat."
  agent: analisa_penyakit

rekomendasi_obat_task:
  description: >
    Berdasarkan daftar penyakit yang telah didiagnosis, berikan rekomendasi obat untuk masing-masing penyakit.
    Setiap penyakit harus memiliki: nama obat, dosis, aturan pakai, dan efek samping yang umum.
  expected_output: >
    Untuk setiap penyakit:
    - Nama penyakit
    - Nama obat
    - Dosis
    - Aturan pakai
    - Efek samping
  agent: apoteker_virtual


output_manager_task:
  description: >
    Merapikan output dari agent lain agar mudah dipahami manusia dalam format yang konsisten dan profesional.
  expected_output: >
    Rangkuman output agent lain dalam format yang ditentukan. Hilangkan tanda bintang pada output, dan berikan new line pada akhir baris. Contoh output:

    1. Nama Penyakit (dengan nama lokal jika ada)\n
    - Tingkat Risiko: Tingkat Risiko Penyakit\n
    - Gejala Terkait: Daftar Gejala\n
    - Efek Samping Umum: Daftar Efek Samping Umum
    - Rekomendasi Obat:
      - Nama Obat: Nama Obat
      - Dosis: Dosis
      - Aturan Pakai: Aturan Pakai
      - Efek Samping Obat: Efek Samping dari Obat
  agent: output_manager
  context: [analisis_penyakit_dari_gejala_task, rekomendasi_obat_task]
